### ISSUE TITLE
[neural-networks] progress bar for training

### ISSUE THREAD

**Issue by HenKlei** [HenKlei/pymor#13]
I think it would be nice to have a small progress bar to see the current state of the training. Especially if training takes longer, some information on the progress might be helpful.

**Comment by HenKlei** [comment]
@sdrave What do you think about this?

**Comment by sdrave** [comment]
Hmm, so far we don't officially have progress bars in pyMOR. When adding such functionality, I would like to do it in a way that is useful elsewhere in pyMOR. Maybe you can open up an issue in the main repo to discuss this? As a short-term alternative, you could simply use the logging mechanism.

**Comment by HenKlei** [comment]
@sdrave What about an additional `logging_frequency` parameter that determines how often to log the current losses? At least for the moment that could be a good compromise.

**Comment by sdrave** [comment]
Maybe even more simplistic: log after each restart?

**Comment by HenKlei** [comment]
Logging for each restart is already the case. Maybe logging during training is also too much. I think at the moment it is fine as is, hence I will close the issue and we will see if and how https://github.com/pymor/pymor/issues/953 processes.
