### ISSUE TITLE
[NeuralNetworkModel] return reduced coordinates

### ISSUE THREAD

**Issue by HenKlei** [HenKlei/pymor#3]
The model should return the coordinates in the reduced basis and not their reconstruction in the high dimensional state.

**Comment by HenKlei** [comment]
@sdrave Maybe you could have a look at 037b576? I made changes addressing this issue as well as #4.

**Comment by sdrave** [comment]
This is basically right, but the result of `solve` always should be a `NumpyVectorArray` not a plain numpy array. You should also define `solution_space` as `NumpyVectorSpace(len(reduced_basis))`. Then you can write `self.solution_space.make_array(u)`.

**Comment by HenKlei** [comment]
Since I just removed `reduced_basis` from `NeuralNetworkModel`, I will use the output dimension of the neural network instead of `len(reduced_basis)`.

**Comment by HenKlei** [comment]
Should be fixed in 25d4f8a.

**Comment by sdrave** [comment]
LGTM.
