### ISSUE TITLE
[tutorial] add a tutorial for the usage of neural networks in pyMOR

### ISSUE THREAD

**Issue by HenKlei** [HenKlei/pymor#5]

**Comment by HenKlei** [comment]
First version in b24c1a4.

**Comment by HenKlei** [comment]
I updated the tutorial in 38992b2, but there still seems to be a problem.

@sdrave Could you have a short look if I'm making something obviously wrong? Thanks!

**Comment by sdrave** [comment]
Does not work for me either. @renefritze should take a look. I cannot see anything wrong.

**Comment by HenKlei** [comment]
@sdrave What about replacing the current example in the tutorial with one using FEniCS? I think a nonlinear example would be more interesting. Or is that too much new stuff at once?

**Comment by sdrave** [comment]
Not sure. It also adds a hard dependency on FEniCS for the tutorial. Maybe leave as is for now or have both versions in the tutorial. (So basically at the end you can write that this also works with external solvers and give a short example.)

**Comment by HenKlei** [comment]
Good idea. I think I will just mention that as a remark.
